import type { Employee } from './types';

// Constante para localStorage
const STORAGE_KEY = 'stafflink_users_db_v2';

// Datos iniciales de empleados
const initialEmployees: Employee[] = [
  {
    id: 'user-1',
    name: 'María',
    surname: 'García López',
    email: 'maria.garcia@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'ADMINISTRADOR'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000001',
    field_oficina: 'MAD',
    field_area: 'ARQ',
    field_department: 'FS',
    field_division: 'TECH',
    field_bu: 'BANK',
    field_categoria: 'DIR',
    field_tipo_carrera: 'MIX',
    skills: ['REACT', 'NODE', 'AWS', 'TS', 'GQL'],
    idiomas: ['ES-NAT', 'EN-C1'],
    field_responsables: []
  },
  {
    id: 'user-2',
    name: 'Carlos',
    surname: 'Rodríguez Pérez',
    email: 'carlos.rodriguez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'RESPONSABLE', 'STAFF'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000002',
    field_oficina: 'MAD',
    field_area: 'DEV',
    field_department: 'FE',
    field_division: 'TECH',
    field_bu: 'BANK',
    field_categoria: 'MGR',
    field_tipo_carrera: 'MGMT',
    skills: ['REACT', 'VUE', 'TS', 'JS'],
    idiomas: ['ES-NAT', 'EN-C1', 'FR-B2'],
    field_responsables: ['user-1']
  },
  {
    id: 'user-3',
    name: 'Ana',
    surname: 'Martínez Sánchez',
    email: 'ana.martinez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'STAFF'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000003',
    field_oficina: 'BCN',
    field_area: 'DEV',
    field_department: 'BE',
    field_division: 'TECH',
    field_bu: 'INS',
    field_categoria: 'SR',
    field_tipo_carrera: 'TECH',
    skills: ['NODE', 'PY', 'JAVA', 'SQL', 'PG'],
    idiomas: ['ES-NAT', 'EN-B2'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-4',
    name: 'David',
    surname: 'Fernández Ruiz',
    email: 'david.fernandez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'RESPONSABLE_STAFFING'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000004',
    field_oficina: 'VLC',
    field_area: 'DEVOPS',
    field_department: 'CLOUD',
    field_division: 'TECH',
    field_bu: 'IND',
    field_categoria: 'EXP',
    field_tipo_carrera: 'TECH',
    skills: ['AWS', 'AZ', 'DOCK', 'K8S'],
    idiomas: ['ES-NAT', 'EN-C1'],
    field_responsables: ['user-1']
  },
  {
    id: 'user-5',
    name: 'Laura',
    surname: 'González Moreno',
    email: 'laura.gonzalez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000005',
    field_oficina: 'BCN',
    field_area: 'DEV',
    field_department: 'FE',
    field_division: 'DIG',
    field_bu: 'RET',
    field_categoria: 'JR',
    field_tipo_carrera: 'TECH',
    skills: ['REACT', 'TS', 'JS'],
    idiomas: ['ES-NAT', 'EN-B2'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-6',
    name: 'Javier',
    surname: 'López Díaz',
    email: 'javier.lopez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'RESPONSABLE'],
    field_estado_empleado: 'inactivo',
    field_num_empleado: '000006',
    field_oficina: 'SEV',
    field_area: 'CONS',
    field_department: 'FS',
    field_division: 'DIG',
    field_bu: 'TEL',
    field_categoria: 'EXP',
    field_tipo_carrera: 'MGMT',
    skills: ['REACT', 'NODE', 'JAVA', 'TS'],
    idiomas: ['ES-NAT', 'EN-C1', 'PT-B1'],
    field_responsables: ['user-1']
  },
  {
    id: 'user-7',
    name: 'Carmen',
    surname: 'Jiménez Torres',
    email: 'carmen.jimenez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'STAFF'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000007',
    field_oficina: 'MAD',
    field_area: 'QA',
    field_department: 'FS',
    field_division: 'TECH',
    field_bu: 'BANK',
    field_categoria: 'SR',
    field_tipo_carrera: 'TECH',
    skills: ['REACT', 'ANG', 'TS', 'REST'],
    idiomas: ['ES-NAT', 'EN-C1'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-8',
    name: 'Pedro',
    surname: 'Sánchez Ruiz',
    email: 'pedro.sanchez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000008',
    field_oficina: 'MAD',
    field_area: 'DEV',
    field_department: 'BE',
    field_division: 'TECH',
    field_bu: 'BANK',
    field_categoria: 'JR',
    field_tipo_carrera: 'TECH',
    skills: ['JAVA', 'SQL', 'SPRING'],
    idiomas: ['ES-NAT', 'EN-B1'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-9',
    name: 'Isabel',
    surname: 'Hernández Castro',
    email: 'isabel.hernandez@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'STAFF'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000009',
    field_oficina: 'BCN',
    field_area: 'DEV',
    field_department: 'FE',
    field_division: 'DIG',
    field_bu: 'RET',
    field_categoria: 'SR',
    field_tipo_carrera: 'TECH',
    skills: ['VUE', 'TS', 'JS', 'CSS'],
    idiomas: ['ES-NAT', 'EN-C1'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-10',
    name: 'Miguel',
    surname: 'Torres Vega',
    email: 'miguel.torres@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000010',
    field_oficina: 'VLC',
    field_area: 'DEV',
    field_department: 'BE',
    field_division: 'TECH',
    field_bu: 'IND',
    field_categoria: 'EXP',
    field_tipo_carrera: 'TECH',
    skills: ['NODE', 'PY', 'MONGO', 'REDIS'],
    idiomas: ['ES-NAT', 'EN-B2'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-11',
    name: 'Lucía',
    surname: 'Moreno Blanco',
    email: 'lucia.moreno@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'RESPONSABLE'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000011',
    field_oficina: 'SEV',
    field_area: 'CONS',
    field_department: 'FS',
    field_division: 'DIG',
    field_bu: 'TEL',
    field_categoria: 'MGR',
    field_tipo_carrera: 'MGMT',
    skills: ['REACT', 'NODE', 'AWS'],
    idiomas: ['ES-NAT', 'EN-C1'],
    field_responsables: ['user-1']
  },
  {
    id: 'user-12',
    name: 'Francisco',
    surname: 'Romero Gil',
    email: 'francisco.romero@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000012',
    field_oficina: 'MAD',
    field_area: 'DEVOPS',
    field_department: 'CLOUD',
    field_division: 'TECH',
    field_bu: 'BANK',
    field_categoria: 'SR',
    field_tipo_carrera: 'TECH',
    skills: ['DOCK', 'K8S', 'JENK', 'GIT'],
    idiomas: ['ES-NAT', 'EN-C1'],
    field_responsables: ['user-4']
  },
  {
    id: 'user-13',
    name: 'Rosa',
    surname: 'Navarro Ortiz',
    email: 'rosa.navarro@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'STAFF'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000013',
    field_oficina: 'BCN',
    field_area: 'QA',
    field_department: 'FS',
    field_division: 'TECH',
    field_bu: 'INS',
    field_categoria: 'EXP',
    field_tipo_carrera: 'TECH',
    skills: ['JAVA', 'SEL', 'REST', 'SQL'],
    idiomas: ['ES-NAT', 'EN-B2'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-14',
    name: 'Antonio',
    surname: 'Muñoz Prieto',
    email: 'antonio.munoz@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000014',
    field_oficina: 'VLC',
    field_area: 'DEV',
    field_department: 'FE',
    field_division: 'TECH',
    field_bu: 'IND',
    field_categoria: 'JR',
    field_tipo_carrera: 'TECH',
    skills: ['ANG', 'TS', 'RxJS'],
    idiomas: ['ES-NAT', 'EN-B1'],
    field_responsables: ['user-2']
  },
  {
    id: 'user-15',
    name: 'Elena',
    surname: 'Ruiz Méndez',
    email: 'elena.ruiz@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'STAFF'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000015',
    field_oficina: 'SEV',
    field_area: 'DEV',
    field_department: 'BE',
    field_division: 'DIG',
    field_bu: 'TEL',
    field_categoria: 'SR',
    field_tipo_carrera: 'TECH',
    skills: ['PY', 'DJANGO', 'PG', 'REDIS'],
    idiomas: ['ES-NAT', 'EN-C1', 'DE-B1'],
    field_responsables: ['user-11']
  },
  {
    id: 'user-16',
    name: 'Jorge',
    surname: 'Díaz Santos',
    email: 'jorge.diaz@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000016',
    field_oficina: 'MAD',
    field_area: 'ARQ',
    field_department: 'FS',
    field_division: 'TECH',
    field_bu: 'BANK',
    field_categoria: 'EXP',
    field_tipo_carrera: 'TECH',
    skills: ['JAVA', 'SPRING', 'MICRO', 'K8S'],
    idiomas: ['ES-NAT', 'EN-C1'],
    field_responsables: ['user-1']
  },
  {
    id: 'user-17',
    name: 'Patricia',
    surname: 'Ortega Fernández',
    email: 'patricia.ortega@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'STAFF'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000017',
    field_oficina: 'BCN',
    field_area: 'DEV',
    field_department: 'FE',
    field_division: 'DIG',
    field_bu: 'RET',
    field_categoria: 'JR',
    field_tipo_carrera: 'TECH',
    skills: ['REACT', 'JS', 'CSS', 'HTML'],
    idiomas: ['ES-NAT', 'EN-B2'],
    field_responsables: ['user-9']
  },
  {
    id: 'user-18',
    name: 'Raúl',
    surname: 'Castro López',
    email: 'raul.castro@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000018',
    field_oficina: 'VLC',
    field_area: 'DEVOPS',
    field_department: 'CLOUD',
    field_division: 'TECH',
    field_bu: 'IND',
    field_categoria: 'SR',
    field_tipo_carrera: 'TECH',
    skills: ['AWS', 'TERR', 'BASH', 'PY'],
    idiomas: ['ES-NAT', 'EN-B2'],
    field_responsables: ['user-4']
  },
  {
    id: 'user-19',
    name: 'Silvia',
    surname: 'Rubio Martín',
    email: 'silvia.rubio@stafflink.com',
    roles: ['USUARIO_AUTENTICADO', 'RESPONSABLE'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000019',
    field_oficina: 'SEV',
    field_area: 'CONS',
    field_department: 'FS',
    field_division: 'DIG',
    field_bu: 'TEL',
    field_categoria: 'EXP',
    field_tipo_carrera: 'MGMT',
    skills: ['JAVA', 'REACT', 'SQL'],
    idiomas: ['ES-NAT', 'EN-C1', 'IT-B1'],
    field_responsables: ['user-11']
  },
  {
    id: 'user-20',
    name: 'Alberto',
    surname: 'Serrano Núñez',
    email: 'alberto.serrano@stafflink.com',
    roles: ['USUARIO_AUTENTICADO'],
    field_estado_empleado: 'activo',
    field_num_empleado: '000020',
    field_oficina: 'MAD',
    field_area: 'QA',
    field_department: 'FS',
    field_division: 'TECH',
    field_bu: 'BANK',
    field_categoria: 'JR',
    field_tipo_carrera: 'TECH',
    skills: ['JAVA', 'SEL', 'JMTR'],
    idiomas: ['ES-NAT', 'EN-B1'],
    field_responsables: ['user-7']
  }
];

// Función para cargar empleados desde localStorage
const loadEmployeesFromStorage = (): Employee[] => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      return JSON.parse(stored);
    }
  } catch (error) {
    console.error('Error al cargar empleados desde localStorage:', error);
  }
  return [...initialEmployees];
};

// Función para guardar empleados en localStorage
export const saveEmployeesToStorage = (employees: Employee[]): void => {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(employees));
  } catch (error) {
    console.error('Error al guardar empleados en localStorage:', error);
  }
};

// Cargar empleados desde localStorage o usar datos iniciales
// eslint-disable-next-line prefer-const
export let employees = loadEmployeesFromStorage();
