/**
 * Mock de datos para Proyecto
 */
import type { Proyecto } from './types';
import { EstadoProyecto } from './types';

export const proyectosMock: Proyecto[] = [
  {
    id: '1',
    title: 'Portal Digital Santander',
    field_cliente: '1',
    field_codigo_proyecto: 'SANT-2024-001',
    field_torre: 'torre-banking',
    field_manager: 'user-1',
    field_manager_proyecto: 'user-2',
    field_lider_tecnico: 'user-3',
    field_area: ['area-frontend', 'area-backend'],
    field_mkt: 'mkt-1',
    field_estado_proyecto: EstadoProyecto.IN_PROGRESS,
    field_start_date: '2026-01-15',
    field_end_date: '2026-12-31',
  },
  {
    id: '2',
    title: 'App Móvil BBVA',
    field_cliente: '2',
    field_codigo_proyecto: 'BBVA-2024-002',
    field_torre: 'torre-banking',
    field_manager: 'user-2',
    field_manager_proyecto: 'user-4',
    field_lider_tecnico: 'user-5',
    field_area: ['area-mobile'],
    field_mkt: 'mkt-2',
    field_estado_proyecto: EstadoProyecto.IN_PROGRESS,
    field_start_date: '2026-03-01',
  },
  {
    id: '3',
    title: 'Migración Cloud Telefónica',
    field_cliente: '3',
    field_codigo_proyecto: 'TEL-2024-003',
    field_torre: 'torre-telecom',
    field_manager: 'user-3',
    field_manager_proyecto: 'user-1',
    field_lider_tecnico: 'user-6',
    field_area: ['area-cloud', 'area-devops'],
    field_mkt: 'mkt-3',
    field_estado_proyecto: EstadoProyecto.PLANNED,
    field_start_date: '2025-06-01',
    field_end_date: '2027-06-01',
  },
  {
    id: '4',
    title: 'E-commerce Inditex',
    field_cliente: '4',
    field_codigo_proyecto: 'IND-2023-004',
    field_torre: 'torre-retail',
    field_manager: 'user-1',
    field_manager_proyecto: 'user-2',
    field_lider_tecnico: 'user-3',
    field_area: ['area-frontend', 'area-backend', 'area-ux'],
    field_mkt: 'mkt-4',
    field_estado_proyecto: EstadoProyecto.COMPLETED,
    field_start_date: '2023-01-01',
    field_end_date: '2023-12-31',
  },
  {
    id: '5',
    title: 'Plataforma Digital Mercadona',
    field_cliente: '5',
    field_codigo_proyecto: 'MER-2024-005',
    field_torre: 'torre-retail',
    field_manager: 'user-4',
    field_manager_proyecto: 'user-11',
    field_lider_tecnico: 'user-10',
    field_area: ['area-frontend', 'area-backend', 'area-mobile'],
    field_mkt: 'mkt-5',
    field_estado_proyecto: EstadoProyecto.IN_PROGRESS,
    field_start_date: '2026-04-01',
    field_end_date: '2026-12-31',
  },
  {
    id: '6',
    title: 'Sistema CRM Telefónica',
    field_cliente: '3',
    field_codigo_proyecto: 'TEL-2024-006',
    field_torre: 'torre-telecom',
    field_manager: 'user-1',
    field_manager_proyecto: 'user-19',
    field_lider_tecnico: 'user-16',
    field_area: ['area-backend', 'area-frontend'],
    field_mkt: 'mkt-6',
    field_estado_proyecto: EstadoProyecto.IN_PROGRESS,
    field_start_date: '2026-02-01',
    field_end_date: '2026-10-31',
  },
];
